config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'plays/showquiz'
  root 'eval_us#index'
  get 'users_profile/edit', to: 'dashboards#edit', as: 'edit_profile'
  get '/edit/:id', to: 'dashboards#update'
  get '/edit_code/:id', to: 'dashboards#edit_code'
  get '/code/:id', to: 'dashboards#update_code'
  get 'showquestion', to: 'plays#showquestion'
  get 'testing', to: 'plays#testing'
  post '/takingtest', to: 'plays#takingtest'
  get '/test_code', to: 'plays#showquestion'
  get '/result', to: 'plays#result'
  get 'quiz/:test_id', to: 'creates#test'
  get '/show_quiz/:test_id', to: 'plays#showquiz', as: :test_id
  get '/show_quiz', to: 'plays#showquiz'
  get '/quiz', to: 'creates#quiz'
  get '/listQuestion', to: 'dashboards#listQuestion'
  get '/explore', to: 'dashboards#explore'
  get '/mylibrary', to: 'dashboards#mylibrary'
  get '/reports', to: 'dashboards#report'
  get '/profile', to: 'dashboards#profile'
  get '/savetolibrary', to: 'creates#save_library'
  get '/save', to: 'creates#add_library'
  post '/finish_quiz', to: 'creates#increase_test_id'
  get '/Question', to: 'dashboards#listQuestion'
  get 'add', to: 'dashboards#add_topic'
  post '/added', to: 'dashboards#added'
  get 'play', to: 'plays#choose'
  get '/home', to: 'eval_us#index'
  get '/register', to: 'users#register'
  post '/create', to: 'users#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'plays/showquestion'
  resources :users
  resources :sessions, only: %i[login create destroy]
  get 'login', to: 'sessions#login', as: 'login'
  get '/logout', to: 'sessions#destroy', as: 'logout'
  # match '/store' , to: 'creates#store' , via: "post"
  post '/store', to: 'creates#store'
  # post '/save', to: 'creates#random'
end

app/controllers/eval_us_controller.rb
# frozen_string_literal: true

class EvalUsController < ApplicationController
  skip_before_action :ensure_user_logged_in
  def index
    @presence = 0
    if current_user
      @presence = 1
      @user = User.find(current_user.id)
    else
      @presence = 0
    end
    render 'eval_us/index'
    @input_list = User.all
  end

  def landingpage; end
end

app/helpers/eval_us_helper.rb
# frozen_string_literal: true

module EvalUsHelper
end

app/views/eval_us/index.html.erb
<style>
  body {
    scroll-behavior: smooth;
    Overflow-y: scroll;
    background-color: white;
    font-family: Poppins;
  }
</style>
<div id="whole_container">
    <div style=" display: flex; flex-direction: row; background-color: blue;">
      <div style="margin-top: -6vw; position: fixed; z-index: 100;">
        <%= image_tag 'EVALU.png' , id: "logo_evalu" %>
      </div>
      <div>
          <ul>
            <li>
              <a href="/home">
                Home
              </a>
            </li>
            <li>
              <% if @presence==1 %>
                <a href="/savetolibrary">
                  Create
                </a>
                <% else %>
                  <a href="#redirect_page" onclick="redirect_page_function()">Create</a>
                  <% end %>
            </li>
            <li>
              <% if @presence==1 %>
                <a href="/mylibrary">
                  Dashboard
                </a>
                <% else %>
                  <a href="#redirect_page" onclick="redirect_page_function()">Dashboard</a>
                  <% end %>
            </li>
            <li style="font-size: 55%; ">
              <% if @presence==1 %>
            <li class="dropdown">
              <%= image_tag "loggedinuser.png" , height: 50, class: 'dropbtn' %>
  
                    <div id="myDropdown" class="dropdown-content">
                      <a href="#"><%= @current_user.username %></a>
                      <a href="/profile" style="color: red; font-size: 25px;"> Profile </a>
                      <a href="/logout" style="color: red; font-size: 25px;"> Logout </a>
                    </div>
                  </div>
                </div>
                <% else %>
                  <%= link_to 'Log In' , login_path %>
                <% end %>
            </li>
          </ul>
      </div>
    </div>

    
    
    <div id="content" style="display: flex; flex-direction: row;">
      <div>
        <!-- <h3 id="fwsa_color" style="top: 13vw;"> FWSA </h3> -->
        <h2 class="text_color" style="margin-top: 4vw; display: flex; flex-direction: row;">
          Welcome To  <span style="font-size: 5vw;"><%= image_tag 'WHITE_LOGO.png' , id: "text_evalu" %></span>
        </h2>
        <p id="tag_text">ENJOY LEARNING</p>
            <button id="btn_style">
             <% if @presence==1 %>
                <a style="text-decoration: none; color: white;" href="play">
                  USE CODE
                </a>
                <% else %>
                <a style="text-decoration: none; color: white;" href="#redirect_page" onclick="redirect_page_function()">
                  USE CODE
                </a>
                  <% end %> 
            </button>
          
      </div>
      <div id="image">
        <%= image_tag 'homepage_image.png', width: '120%', height: 'auto', id: 'image_blur', style: 'margin-top: 2.1vw; margin-left: 0vw;  margin-right: 0vw;'%>
      </div>
    </div>

    <div style="display: flex; flex-direction: row;">
      <div class="short_note">
        <%= image_tag 'Q&A.png', width: '55%', height: 'auto', id: 'image_blur', style: 'margin-top: 2.1vw; margin-left: 0vw;  margin-right: 0vw;'%>
        <h2 class="head">Create Your Own Questions</h2>
        <p>You can create questions for your peers or students to assess them.</p>
      </div>
      <div class="short_note">
        <%= image_tag 'taketest.png', width: '55%', height: 'auto', id: 'image_blur', style: 'margin-top: 2.1vw; margin-left: 0vw;  margin-right: 0vw;'%>
        <h2 class="head">Take Test</h2>
        <p>You can take your test by using the test code</p>
      </div>
      <div class="short_note">
        <%= image_tag 'Analytics.png', width: '45%', height: 'auto', id: 'image_blur', style: 'margin-top: 2.1vw; margin-left: 0vw;  margin-right: 0vw;'%>
        <h2 class="head" style="margin-top: 1vw;">Report</h2>
        <p>Report that helps you to know your performance</p>
      </div>
    </div>
    
    <div id="footer">
      <div style="display: flex; flex-direction: column;">
        <div>
          <%= image_tag 'EVALU.png' , id: "footer_evalu" %>
        </div>
        <div style="display: flex; flex-direction: row; color: #F96972;">
          <a href="" style="margin-top: 4vw; margin-left: 26vw;">About</a>
          <a href="" style="margin-top: 4vw;">Feedback</a>
          <a href="" style="margin-top: 4vw;">Help</a>
          <a href="" style="margin-top: 4vw;">Contact</a>
        </div>
      </div>
      <div style="margin-left: 35vw;">
        <%= image_tag 'Insta.png' , class: "footer_image" %>
        <%= image_tag 'linkedIN.png' , class: "footer_image" %>
        <%= image_tag 'Utube.png' , class: "footer_image" %>
        <%= image_tag 'facebook.png' , class: "footer_image" %>
      </div>
      <span style="margin-left: 40vw; font-family: Poppins;">Copyright © 2022, EVAL<b>U</b>..! All Rights Reserved.</span>
    </div> 
</div>

 
    <div id="enter_code" style=" background-color: #24B7C6; display: none;">
      <a href="/home">
        <%= image_tag 'wrong_sym.png' , id: "wrong_symbol" %>  
      </a>
      <%= form_with url: "/quiz/test_id:" , model:@search do |form| %>  
        <%= form.text_field :code, id: 'code_id', placeholder: "Enter code" %> <br>
        <input id="enter_btn" type="submit" value="Enter">
      <% end %>
    </div>
 
  
<div id="redirect_page" style="background-color: #24B7C6; display: none; text-align: center; ">
  <a href="/home">
    <%= image_tag 'wrong_sym.png' , id: "wrong_symbol" %>  
  </a>
  <span style="color: white; font-size: 1vw; font-family: Poppins; margin-top: 5vw;">You should Log in first,<br> To continue your work in  EVAL<b>U</b></span> <br>
  <button style="background-color: #F96972; border-color: #F96972; width: 6vw; height: auto; font-size: 1.2vw; padding: 5px; margin-top: 5vw;" > <%= link_to 'Log in' , login_path, style: 'text-decoration: none; color: white;' %></button> 
</div>


<script>
  function clicked(){
    document.getElementById("whole_container").style.display = "none";
    document.getElementById("enter_code").style.display = "block";
  }

  function redirect_page_function() {
    event.preventDefault();
    document.getElementById("whole_container").style.display = "none";
    document.getElementById("redirect_page").style.display = "block";
  }
  
  function myFunction() {
  document.getElementById("myDropdown").classList.toggle("show");
}

// Close the dropdown menu if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {
    let dropdowns = document.getElementsByClassName("dropdown-content");
    let i;
    for (i = 0; i < dropdowns.length; i++) {
      let openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
 
</script>

app/views/eval_us/landingpage.html.erb
<%= image_tag 'EVALU.png' , id: "logo_evalu", style: 'position: fixed' %>
<div style="display: flex; flex-direction: row;">
    <div>
      <h3 id="fwsa_color" style="top: 13vw;"> FWSA </h3>
      <h2 class="text_color" style="margin-top: 8vw;">
        Assess yourself by <span style="font-size: 5vw;"> <%= image_tag 'EVALU.png' , id: "text_evalu", style: 'position: fixed' %>
</span>
      </h2>
      <%# <h3 id="fwsa_color">
        Let's start your
        </h3> %>
        <button id="btn_style">
            <a href="/home" style="text-decoration: none; color: white;">
              Lets go
            </a>
        </button>
    </div>
    <div id="image_div">
      <%= image_tag 'akkabg.png' , style: 'height:45vw; width:42vw; margin-top: 3vw;' %>
    </div>
  </div>